[package]
name = "collector"
version = "0.0.1"
authors = ["Đorđe Zeljić <zeljic@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.13.0"

serde = "1.0.83"
serde_json = "1.0.33"
serde_derive = "1.0.83"

rocket = "0.4.0"
rocket_codegen = "0.4.0"
rocket_contrib = { version = "0.4.0", default-features = false, features = ["json"] }

r2d2 = "0.8.3"
r2d2_sqlite = "0.7.0"
rusqlite = "0.15.0"

rust-crypto = "0.2.36"

rand = "0.6.1"
