[package]
name = "collector"
version = "0.0.1"
authors = ["Đorđe Zeljić <zeljic@gmail.com>"]
edition = "2018"

[dependencies]
rust-crypto = "0.2.36"
rand = "0.6.4"

serde = "1.0.85"
serde_json = "1.0.37"
serde_derive = "1.0.85"

rocket = "0.4.0"
rocket_codegen = "0.4.0"
rocket_contrib = { version = "0.4.0", default-features = false, features = ["json", "diesel_sqlite_pool"] }

[dependencies.diesel]
version = "1.4.1"
features = ["sqlite"]
